#!/usr/bin/osascript


-- This AppleScript gets default browser tabs and prints them to stdout

-- Initialize URL text file
set cmd to ""

-- Write urls to file: Change "Safari" to preferred browser
tell application "Safari"
    set n to count of tabs in front window
    repeat with i from 1 to n
        set cmd to cmd & URL of tab i of front window & linefeed
    end repeat
end tell

-- Print to stdout
return cmd
